version: "3.5"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/xywgo/data/docker/config/qbittorrent:/config
      - /home/xywgo/data/media:/downloads
    ports:
      - 7000:7000
      - 7000:7000/udp
      - 8080:8080
    restart: unless-stopped
  flexget:
    image: xywgo/flexget
    container_name: flexget
    restart: always
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PASSWD=Mm451048163
    ports: 
      - "8600:8600"
    volumes: 
      - /home/xywgo/data/media/torrents:/torrents
      - /home/xywgo/data/docker/config/flexget:/config
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8900:80"
    volumes:
      - /home/xywgo/data:/srv
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    volumes: 
      - /home/xywgo/data/docker/config/aria2:/config
      - /home/xywgo/data/Others:/downloads
    environment: 
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=xywgo
      - TZ=Asia/Shanghai
      - TRACKERS=no
      - DISK_CACHE=64M
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
  plex:
    image: ghcr.io/linuxserver/plex
    network_mode: host
    container_name: plex
    volumes:
      - /home/xywgo/data/media:/media:rw # The media folder
      - /home/xywgo/data/media:/transcode # Transcoder temporary directory
      - /home/xywgo/data/docker/config/plex:/config # Configurations
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=claim-46KzwRxxaixzsx_e_YX9 # Replace this TOKEN!!! acess https://www.plex.tv/claim/ to get it
      - UMASK_SET=022 #optional
    restart: unless-stopped
    hostname: "BuyVM" # change the name to whatever you like
  # resilio-sync:
  #   image: ghcr.io/linuxserver/resilio-sync
  #   container_name: resilio-sync
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Shanghai
  #     - UMASK_SET=022
  #   volumes:
  #     - /home/xywgo/data/docker/config/resilio:/config
  #     - /home/xywgo/downloads:/downloads
  #     - /home/xywgo/downloads:/sync
  #   ports:
  #     - 8886:8888
  #     - 55555:55555
  #   restart: unless-stopped
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/xywgo/data/docker/config/syncthing:/config
      - /home/xywgo/data/media:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    # docker run -d -p 8000:8000 -p 9000:9000 --name portainer \
    # --restart=always \
    # -v /var/run/docker.sock:/var/run/docker.sock \
    # -v /home/xywgo/data/docker/portainer:/data \
    # portainer/portainer-ce:latest
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:latest
    container_name: PhotoPrism
    depends_on:
      - mariadb
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "Mm451048163"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # Disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # Disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # Disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      ## Hardware video transcoding config (optional)
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # Use Video4Linux for AVC transcoding (default: libx264)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"        # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
      # PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2" # Enable TensorFlow AVX2 & Intel Graphics support
      ## Enable TensorFlow AVX2 support for modern Intel CPUs (requires starting the container as root)
      # PHOTOPRISM_INIT: "tensorflow-amd64-avx2"
      ## Run as a specific user, group, or with a custom umask (does not work together with "user:")
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      HOME: "/photoprism"
    ## Start as a non-root user (see https://docs.docker.com/engine/reference/run/#user)
    # user: "1000:1000"
    ## Hardware devices for video transcoding and machine learning (optional)
    # devices:
    #  - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    #  - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
    #  - "/dev/dri/card0:/dev/dri/card0"
    working_dir: "/photoprism"
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      # "/host/folder:/photoprism/folder"                # example
      - "/home/xywgo/data/media:/photoprism/originals"               # original media files (photos and videos)
      # - "/example/family:/photoprism/originals/family" # *additional* media folders can be mounted like this
      # - "~/Import:/photoprism/import"                  # *optional* base folder from which files can be imported to originals
      - "/home/xywgo/data/storage:/photoprism/storage"                  # *writable* storage folder for cache, database, and sidecar files (never remove)

  ## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: mariadb:10.6
    container_name: mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql" # Important, don't remove
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

  ## Watchtower upgrades services automatically (optional)
  ## see https://docs.photoprism.app/getting-started/updates/#watchtower
  #
  # watchtower:
  #   restart: unless-stopped
  #   image: containrrr/watchtower
  #   environment:
  #     WATCHTOWER_CLEANUP: "true"
  #     WATCHTOWER_POLL_INTERVAL: 7200 # checks for updates every two hours
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "~/.docker/config.json:/config.json" # Optional, for authentication if you have a Docker Hub account
  emby:
  image: lscr.io/linuxserver/emby
  container_name: emby
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
  volumes:
    - /home/xywgo/data/docker/config/emby:/config
    - /home/xywgo/data/media:/data/media
    # - /path/to/movies:/data/movies
    # - /opt/vc/lib:/opt/vc/lib #optional
  ports:
    - 8096:8096
    # - 8920:8920 #optional
  # devices:
  #   - /dev/dri:/dev/dri #optional
  #   - /dev/vchiq:/dev/vchiq #optional
  #   - /dev/video10:/dev/video10 #optional
  #   - /dev/video11:/dev/video11 #optional
  #   - /dev/video12:/dev/video12 #optional
  restart: unless-stopped