version: "3"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/qbittorrent:/config
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/media:/downloads
    ports:
      - 7000:7000
      - 7000:7000/udp
      - 8080:8080
    restart: unless-stopped
  flexget:
    image: xywgo/flexget
    container_name: flexget
    restart: always
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PASSWD=Mm451048163
    ports: 
      - "8600:8600"
    volumes: 
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/media/torrents:/torrents
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/flexget:/config
  # filebrowser:
  #   image: filebrowser/filebrowser
  #   container_name: filebrowser
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6:/srv
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   restart: unless-stopped
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    volumes: 
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/aria2:/config
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/Others:/downloads
    environment: 
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=xywgo
      - TZ=Asia/Shanghai
      - TRACKERS=no
      - DISK_CACHE=64M
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
  plex:
    image: ghcr.io/linuxserver/plex
    network_mode: host
    container_name: plex
    volumes:
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/media:/media:rw # The media folder
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/media:/transcode # Transcoder temporary directory
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/plex:/config # Configurations
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=claim-46KzwRxxaixzsx_e_YX9 # Replace this TOKEN!!! acess https://www.plex.tv/claim/ to get it
      - UMASK_SET=022 #optional
    restart: unless-stopped
    hostname: "BuyVM" # change the name to whatever you like
  # resilio-sync:
  #   image: ghcr.io/linuxserver/resilio-sync
  #   container_name: resilio-sync
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Shanghai
  #     - UMASK_SET=022
  #   volumes:
  #     - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/resilio:/config
  #     - /home/xywgo/downloads:/downloads
  #     - /home/xywgo/downloads:/sync
  #   ports:
  #     - 8886:8888
  #     - 55555:55555
  #   restart: unless-stopped
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/docker/config/syncthing:/config
      - /srv/dev-disk-by-uuid-9ee3d524-c27c-437c-8301-deb7c20607b6/media:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped