version: "3"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/xywgo/data/docker/config/qbittorrent:/config
      - /home/xywgo/data/media:/downloads
    ports:
      - 7000:7000
      - 7000:7000/udp
      - 8080:8080
    restart: unless-stopped
  flexget:
    image: xywgo/flexget
    container_name: flexget
    restart: always
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PASSWD=Mm451048163
    ports: 
      - "8600:8600"
    volumes: 
      - /home/xywgo/data/media/torrents:/torrents
      - /home/xywgo/data/docker/config/flexget:/config
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8900:80"
    volumes:
      - /home/xywgo/data:/srv
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    volumes: 
      - /home/xywgo/data/docker/config/aria2:/config
      - /home/xywgo/data/Others:/downloads
    environment: 
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=xywgo
      - TZ=Asia/Shanghai
      - TRACKERS=no
      - DISK_CACHE=64M
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
  plex:
    image: ghcr.io/linuxserver/plex
    network_mode: host
    container_name: plex
    volumes:
      - /home/xywgo/data/media:/media:rw # The media folder
      - /home/xywgo/data/media:/transcode # Transcoder temporary directory
      - /home/xywgo/data/docker/config/plex:/config # Configurations
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=claim-46KzwRxxaixzsx_e_YX9 # Replace this TOKEN!!! acess https://www.plex.tv/claim/ to get it
      - UMASK_SET=022 #optional
    restart: unless-stopped
    hostname: "BuyVM" # change the name to whatever you like
  # resilio-sync:
  #   image: ghcr.io/linuxserver/resilio-sync
  #   container_name: resilio-sync
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Shanghai
  #     - UMASK_SET=022
  #   volumes:
  #     - /home/xywgo/data/docker/config/resilio:/config
  #     - /home/xywgo/downloads:/downloads
  #     - /home/xywgo/downloads:/sync
  #   ports:
  #     - 8886:8888
  #     - 55555:55555
  #   restart: unless-stopped
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/xywgo/data/docker/config/syncthing:/config
      - /home/xywgo/data/media:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    # docker run -d -p 8000:8000 -p 9000:9000 --name portainer \
    # --restart=always \
    # -v /var/run/docker.sock:/var/run/docker.sock \
    # -v /home/xywgo/data/docker/portainer:/data \
    # portainer/portainer-ce:latest